###########################################################
### Reads the Energy form the text files generated by the root average values
### If the average is 0 (in case of no beam) it takes the value from
###  the Start of the Run epics file
###########################################################

import numpy as np
import math
import matplotlib.pyplot as plt
import sys
import pathlib

f = input("Enter file: Dec (1), Spring RHRS (2),Spring LHRS (3), Fall RHRS (4): ") 

if int(f) ==1:
	txtfile ='Run_Energy.dat_sdec' 
elif int(f) ==2:
	txtfile ='Run_Energy.dat_spring' 
elif int(f) ==3:
	txtfile ='Run_Energy.dat_LHRSspring'
elif int(f) ==4:
	txtfile ='Run_Energy.dat_fall' 
else:
	sys.exit('Not a valid option')	

run0=[];en0=[];run1=[];en1=[];
run = 0
energy = 0
with open(txtfile) as dat:
	for line in dat:
		if line[0].isdigit():
			data = line.split()
			run = data[0]
			if float(data[1])==0:
				epicsfile ='/work/halla/triton/nathaly/epics/End_of_Run_'+str(data[0])+'.epics'
				pathepics = pathlib.Path(epicsfile)
				if pathepics.exists():
					print('run is in epics folder')
				else:
					continue
						
				with open(epicsfile) as dat2:
        				for line in dat2:
                				data1 = line.split(':')
                				if data1[0] == "Tiefenbach 6GeV Beam energy (MeV) ":
                        				energy=float(data1[1])
			else:
				energy=float(data[1])				
			print(run+'  '+str(energy))
			with open('energyuncalibrated.txt', 'a') as f:
    				f.write(run+'  '+str(energy)+'\n')
